---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:16.2.1
  amd64: ghcr.io/home-assistant/amd64-base:16.2.1
  armhf: ghcr.io/home-assistant/armhf-base:16.2.1
  armv7: ghcr.io/home-assistant/armv7-base:16.2.1
  i386: ghcr.io/home-assistant/i386-base:16.2.1
