name: Whatsapp
version: "1.6.0"
slug: whatsapp_addon
description: Whatsapp addon for send message from Home Assistant
url: "https://github.com/ConstableW/ha-whatsapp/tree/main/whatsapp_addon"
homeassistant_api: true
hassio_api: true
hassio_role: manager
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - "homeassistant_config:rw"
  - media:rw
options:
  clients:
    - default
schema:
  clients:
    - str
